name: Run

on: push

jobs:
  gradle-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: ['8', '11', '17']
    runs-on: ${{ matrix.os }}
    name: Test Java ${{ matrix.java-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.3.1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
    - uses: GabrielBB/xvfb-action@v1
      with:
        run: ./gradlew run --no-daemon
